name: CD - Deploy Producción

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Preparar SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H 137.184.127.11 >> ~/.ssh/known_hosts

      - name: Deploy a Producción
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes alumno@137.184.127.11 "
            cd ~/lemp-sites/valentin_belone/prod && \
            git fetch origin main && \
            git reset --hard origin/main
          "
